# Базовые настройки сайта
title: Ваш сайт
description: Описание вашего сайта
baseurl: "/charts"  # Указывает что сайт находится в подкаталоге /charts
url: "https://a-berez.github.io"

# Настройки URL
permalink: /:title/

# Настройки для GitHub Pages
github:
  is_project_page: true
  repository_url: https://github.com/a-berez/charts

# Исключения из сборки
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Включить редиректы
plugins:
  - jekyll-redirect-from

# Настройки редиректов
redirect_from:
  vvl_mol_chart.html: /charts/vvl25
